server:
  host: "0.0.0.0"
  port: 8080
  features:
    static-content:
      classpath:
        - context: "/ui"
          location: "/WEB"
          welcome: "index.html"

langchain4j:
  # Optional common configuration for all models from the provider
  providers:
    open-ai:
      api-key: "${OPEN_AI_TOKEN}"

  models:
    openai-cheap-model:
      provider: open-ai
      # api-key is in the common provider section
      model-name: "gpt-4o-mini"

    gemini-flash-model:
      provider: google-gemini
      # Or it can be directly in model config
      api-key: "${GEMINI_TOKEN}"
      model-name: "gemini-3-flash-preview"

  embedding-stores:
    se-embedding-store:
      provider: helidon
    mp-embedding-store:
      provider: helidon

  content-retrievers:
    se-content-retriever:
      provider: helidon
      max-results: 10
      min-score: 0.6
      embedding-model: all-mini-lm-l6v2-embedding-model
      embedding-store: se-embedding-store

    mp-content-retriever:
      provider: helidon
      max-results: 10
      min-score: 0.6
      embedding-model: all-mini-lm-l6v2-embedding-model
      embedding-store: mp-embedding-store

app:
  helidon-docs-path: ./helidon-docs
  inclusions: "*.adoc"