server:
  host: "0.0.0.0"
  port: 8080

langchain4j:
  open-ai:
    chat-model:
#      enabled: true
      api-key: "demo"
      model-name: "gpt-4o-mini"
  oci-gen-ai:
    chat-model:
      enabled: true
      model-name: google.gemini-2.5-pro
      compartment-id: "ocid1.tenancy.oc1..aaaaaaaaxilnwwvabfgujrf7ymnkwhfykiaq3qsoxotd5hd53rm3hpclzeaa"
      region: us-phoenix-1

  rag:
    embedding-store-content-retriever:
      enabled: true
      max-results: 10
      min-score: 0.6

app:
  root: "/home/daniel/idp/ora/helidon/helidon-4/docs/src/main/asciidoc"
  inclusions: "*.adoc"