///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.data.sql.datasource.DataSourceConfig
:keywords: helidon, config, io.helidon.data.sql.datasource.DataSourceConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.data.sql.datasource.DataSourceConfig
include::{rootdir}/includes/attributes.adoc[]

= DataSourceConfig (data.sql.datasource) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.data.sql.datasource/io/helidon/data/sql/datasource/DataSourceConfig.html[io.helidon.data.sql.datasource.DataSourceConfig]


This is a standalone configuration type, prefix from configuration root: `data.sources.sql`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`name` |string |`@default` |javax.sql.DataSource name.
Optional name to distinguish several data sources of the same type.
First available data source is returned when name is not set.
|`provider` |io.helidon.data.sql.datasource.ProviderConfig (service provider interface)

Such as:

 - xref:{rootdir}/config/io_helidon_data_sql_datasource_hikari_HikariDataSourceConfig.adoc[hikari (HikariDataSourceConfig)]
 - xref:{rootdir}/config/io_helidon_data_sql_datasource_jdbc_JdbcDataSourceConfig.adoc[jdbc (JdbcDataSourceConfig)]
 - xref:{rootdir}/config/io_helidon_data_sql_datasource_ucp_UcpDataSourceConfig.adoc[ucp (UcpDataSourceConfig)]

 |{nbsp} |Configuration of the used provider, such as UCP.

|===

// end::config[]