///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.http.media.gson.GsonSupport
:keywords: helidon, config, io.helidon.http.media.gson.GsonSupport
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.http.media.gson.GsonSupport
include::{rootdir}/includes/attributes.adoc[]

= GsonSupport (http.media.gson) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.http.media.gson/io/helidon/http/media/gson/GsonSupport.html[io.helidon.http.media.gson.GsonSupport]


[source,text]
.Config key
----
gson
----


This type provides the following service implementations:

- `io.helidon.http.media.spi.MediaSupportProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`name` |string |`gson` |Name of the support. Default value is `gson`.
|`properties` |Map&lt;string, boolean&gt; |{nbsp} |Gson configuration properties.
Properties are being ignored if specific Gson is set.
Only `boolean` configuration values are supported.

|===

// end::config[]