///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.scheduling.FixedRate
:keywords: helidon, config, io.helidon.scheduling.FixedRate
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.scheduling.FixedRate
include::{rootdir}/includes/attributes.adoc[]

= FixedRate (scheduling) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.scheduling/io/helidon/scheduling/FixedRate.html[io.helidon.scheduling.FixedRate]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|[.line-through]#`delay`# |long |{nbsp} |*Deprecated* Fixed rate delay between each invocation. Time unit is by default java.util.concurrent.TimeUnit.SECONDS,
can be specified with io.helidon.scheduling.FixedRateConfig.Builder.timeUnit(java.util.concurrent.TimeUnit).

@deprecated use io.helidon.scheduling.FixedRateConfig.interval() instead
|[.line-through]#`initial-delay`# |long |{nbsp} |*Deprecated* Initial delay of the first invocation. Time unit is by default java.util.concurrent.TimeUnit.SECONDS,
can be specified with
io.helidon.scheduling.FixedRateConfig.Builder.timeUnit(java.util.concurrent.TimeUnit) timeUnit().

@deprecated use io.helidon.scheduling.FixedRateConfig.delayBy() instead
|`interval` |Duration |{nbsp} |Fixed interval between each invocation.

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`delay-by` |Duration |`PT0S` |Initial delay of the first invocation.
|`delay-type` |DelayType (SINCE_PREVIOUS_START, SINCE_PREVIOUS_END) |`DelayType.SINCE_PREVIOUS_START` |Configure whether the interval between the invocations should be calculated from the time when previous task
started or ended.
Delay type is by default FixedRate.DelayType.SINCE_PREVIOUS_START.

Allowed values:

- `SINCE_PREVIOUS_START`: Next invocation start is measured from the previous invocation task start.
- `SINCE_PREVIOUS_END`: Next invocation start is measured from the previous invocation task end.

|`enabled` |boolean |`true` |Whether the task is enabled. If disabled, the task will not be scheduled.
Default value is `true`.
|`id` |string |{nbsp} |Identification of the started task. This can be used to later look up the instance, for example to cancel it.
|[.line-through]#`time-unit`# |TimeUnit (NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS) |`TimeUnit.TimeUnit.SECONDS` |*Deprecated* java.util.concurrent.TimeUnit TimeUnit used for interpretation of values provided with
io.helidon.scheduling.FixedRateConfig.Builder.delay(long)
and io.helidon.scheduling.FixedRateConfig.Builder.initialDelay(long).

@deprecated as duration is used for new options, this option is not needed

|===

// end::config[]