///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.context.ContextFeature
:keywords: helidon, config, io.helidon.webserver.context.ContextFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.context.ContextFeature
include::{rootdir}/includes/attributes.adoc[]

= ContextFeature (webserver.context) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.context/io/helidon/webserver/context/ContextFeature.html[io.helidon.webserver.context.ContextFeature]


[source,text]
.Config key
----
context
----


This type provides the following service implementations:

- `io.helidon.webserver.spi.ServerFeatureProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`records` |xref:{rootdir}/config/io_helidon_common_context_http_ContextRecordConfig.adoc[ContextRecordConfig[&#93;] |{nbsp} |List of propagation records.
|`sockets` |string[&#93; |{nbsp} |List of sockets to register this feature on. If empty, it would get registered on all sockets.
|`weight` |double |`1100.0` |Weight of the context feature. As it is used by other features, the default is quite high:
`1100.0`.

|===

// end::config[]