///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.staticcontent.ClasspathHandlerConfig
:keywords: helidon, config, io.helidon.webserver.staticcontent.ClasspathHandlerConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.staticcontent.ClasspathHandlerConfig
include::{rootdir}/includes/attributes.adoc[]

= ClasspathHandlerConfig (webserver.staticcontent) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.staticcontent/io/helidon/webserver/staticcontent/ClasspathHandlerConfig.html[io.helidon.webserver.staticcontent.ClasspathHandlerConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cached-files` |string[&#93; |{nbsp} |A set of files that are cached in memory at startup. These files are never removed from the in-memory cache, though
their overall size is added to the memory cache used bytes.
When using classpath, the set must contain explicit list of all files that should be cached, when using file system,
it can contain a directory, and all files under that directory (recursive) would be cached as well.

Note that files cached through this method may use more than the max-bytes configured for the in-memory cache (i.e.
this option wins over the maximal size in bytes), so kindly be careful with what is pushed to the cache.

_Files cached in memory will never be re-loaded, even if changed, until server restart!_
|`content-types` |Map&lt;string, MediaType&gt; |{nbsp} |Maps a filename extension to the response content type.
To have a system-wide configuration, you can use the service loader SPI
io.helidon.common.media.type.spi.MediaTypeDetector.

This method can override io.helidon.common.media.type.MediaTypes detection
for a specific static content handler.

Handler will use a union of configuration on the io.helidon.webserver.staticcontent.StaticContentConfig and
here when used from configuration.
|`context` |string |`/` |Context that will serve this handler's static resources, defaults to `/`.
|`enabled` |boolean |`true` |Whether this handle is enabled, defaults to `true`.
|`location` |string |{nbsp} |The location on classpath that contains the root of the static content.
This should never be the root (i.e. `/`), as that would allow serving of all class files.
|`memory-cache` |xref:{rootdir}/config/io_helidon_webserver_staticcontent_MemoryCache.adoc[MemoryCache] |{nbsp} |Handles will use memory cache configured on StaticContentConfig.memoryCache() by default.
In case a memory cache is configured here, it will replace the memory cache used by the static content feature, and this
handle will use a dedicated memory cache instead.

To disable memory caching for a single handler, create the configuration, and set `enabled: false`.
|`record-cache-capacity` |int |{nbsp} |Configure capacity of cache used for resources. This cache will make sure the media type and location is discovered
faster.

To cache content (bytes) in memory, use io.helidon.webserver.staticcontent.BaseHandlerConfig.memoryCache()
|`single-file` |boolean |{nbsp} |Classpath content usually starts from a ClasspathHandlerConfig.location() on classpath, and resolves all
requested paths against this content root.
When this property is set to `true` we consider the `location` to be a file, that is returned for any
requested path under the configured ClasspathHandlerConfig.context().

Note that when this is used, there will never be a redirect returned.
|`sockets` |string[&#93; |{nbsp} |Sockets names (listeners) that will host this static content handler, defaults to all configured sockets.
Default socket name is `@default`.
|`temporary-storage` |xref:{rootdir}/config/io_helidon_webserver_staticcontent_TemporaryStorage.adoc[TemporaryStorage] |{nbsp} |Customization of temporary storage configuration.
|`welcome` |string |{nbsp} |Welcome-file name. In case a directory is requested, this file would be served if present.
There is no welcome file by default.

|===

// end::config[]