///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.data.sql.datasource.ucp.UcpDataSourceConfig
:keywords: helidon, config, io.helidon.data.sql.datasource.ucp.UcpDataSourceConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.data.sql.datasource.ucp.UcpDataSourceConfig
include::{rootdir}/includes/attributes.adoc[]

= UcpDataSourceConfig (data.sql.datasource.ucp) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.data.sql.datasource.ucp/io/helidon/data/sql/datasource/ucp/UcpDataSourceConfig.html[io.helidon.data.sql.datasource.ucp.UcpDataSourceConfig]


[source,text]
.Config key
----
ucp
----


This type provides the following service implementations:

- `io.helidon.data.sql.datasource.spi.DataSourceConfigProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`abandoned-connection-timeout` |int |{nbsp} |Sets the abandoned connection timeout.
See oracle.ucp.jdbc.PoolDataSource.setAbandonedConnectionTimeout(int) for details.
|`commit-on-connection-return` |boolean |{nbsp} |Sets the `boolean` value for the property that controls the behavior of UCP
when a connection is released back to the pool with pending uncommitted changes
in an active transaction.
See oracle.ucp.jdbc.PoolDataSource.setCommitOnConnectionReturn(boolean) for details.
|`connection-factory-class-name` |string |{nbsp} |Sets the connection factory class name.
See oracle.ucp.jdbc.PoolDataSource.setConnectionFactoryClassName(String) for details.
|`connection-factory-properties` |Map |{nbsp} |Sets the connection factory properties on the connection factory.
See oracle.ucp.jdbc.PoolDataSource.setConnectionFactoryProperties(java.util.Properties) for details.
|`connection-harvest-max-count` |int |{nbsp} |Sets the maximum number of connections that may be harvested when the connection harvesting
occurs.
See oracle.ucp.jdbc.PoolDataSource.setConnectionHarvestMaxCount(int) for details.
|`connection-harvest-trigger-count` |int |{nbsp} |Sets the number of available connections below which the connection pool's connection harvesting
will occur.
See oracle.ucp.jdbc.PoolDataSource.setConnectionHarvestTriggerCount(int) for details.
|`connection-labeling-high-cost` |int |{nbsp} |Sets the cost value which identifies a connection as "high-cost" for connection labeling.
See oracle.ucp.jdbc.PoolDataSource.setConnectionLabelingHighCost(int) for details.
|`connection-pool-name` |string |{nbsp} |Sets the connection pool name.
See oracle.ucp.jdbc.PoolDataSource.setConnectionPoolName(String) for details.
|`connection-properties` |Map |{nbsp} |Sets the connection properties on the connection factory.
See oracle.ucp.jdbc.PoolDataSource.setConnectionProperties(java.util.Properties) for details.
|`connection-repurpose-threshold` |int |{nbsp} |Sets the connection repurpose threshold for the pool.
See oracle.ucp.jdbc.PoolDataSource.setConnectionRepurposeThreshold(int) for details.
|`connection-validation-timeout` |int |{nbsp} |Sets the connection validation timeout in seconds.
See oracle.ucp.jdbc.PoolDataSource.setConnectionValidationTimeout(int) for details.
|`connection-wait-duration` |Duration |{nbsp} |Configures how much time a connection request call may wait before it either successfully
returns a connection or throws an exception.
See oracle.ucp.jdbc.PoolDataSource.setConnectionWaitDuration(java.time.Duration) for details.
|`create-connection-in-borrow-thread` |boolean |{nbsp} |Set this flag to `true` to make UCP use the borrowing thread to create new connections.
See oracle.ucp.jdbc.PoolDataSource.setCreateConnectionInBorrowThread(boolean) for details.
|`data-source-name` |string |{nbsp} |Sets the data source name.
See oracle.ucp.jdbc.PoolDataSource.setDataSourceName(String) for details.
|`database-name` |string |{nbsp} |Sets the database name.
See oracle.ucp.jdbc.PoolDataSource.setDatabaseName(String) for details.
|`description` |string |{nbsp} |Sets the data source description.
See oracle.ucp.jdbc.PoolDataSource.setDescription(String) for details.
|`fast-connection-failover-enabled` |boolean |{nbsp} |Enables Fast Connection Failover (FCF) for the connection pool accessed using this pool-enabled data source.
See oracle.ucp.jdbc.PoolDataSource.setFastConnectionFailoverEnabled(boolean) for details.
|`high-cost-connection-reuse-threshold` |int |{nbsp} |Sets the high-cost connection reuse threshold for connection labeling.
See oracle.ucp.jdbc.PoolDataSource.setHighCostConnectionReuseThreshold(int) for details.
|`inactive-connection-timeout` |int |{nbsp} |Sets the inactive connection timeout.
See oracle.ucp.jdbc.PoolDataSource.setInactiveConnectionTimeout(int) for details.
|`initial-pool-size` |int |{nbsp} |Sets the initial pool size.
See oracle.ucp.jdbc.PoolDataSource.setInitialPoolSize(int) for details.
|`max-connection-reuse-count` |int |{nbsp} |Sets the maximum connection reuse count.
See oracle.ucp.jdbc.PoolDataSource.setMaxConnectionReuseCount(int) for details.
|`max-connection-reuse-time` |long |{nbsp} |Sets the maximum connection reuse time in seconds.
See oracle.ucp.jdbc.PoolDataSource.setMaxConnectionReuseTime(long) for details.
|`max-connections-per-shard` |int |{nbsp} |Sets the max number of connections that can be created per shard from this connection pool.
See oracle.ucp.jdbc.PoolDataSource.setMaxConnectionsPerShard(int) for details.
|`max-idle-time` |int |{nbsp} |Sets the maximum idle time for available connections in the pool in seconds.
See oracle.ucp.jdbc.PoolDataSource.setMaxIdleTime(int) for details.
|`max-pool-size` |int |{nbsp} |Sets the maximum number of connections.
See oracle.ucp.jdbc.PoolDataSource.setMaxPoolSize(int) for details.
|`max-statements` |int |{nbsp} |Sets the maximum number of statements that may be pooled or cached on a connection.
See oracle.ucp.jdbc.PoolDataSource.setMaxStatements(int) for details.
|`min-idle` |int |{nbsp} |Sets the minimum number of idle connections.
See oracle.ucp.jdbc.PoolDataSource.setMinIdle(int) for details.
|`min-pool-size` |int |{nbsp} |Sets the minimum number of connections.
See oracle.ucp.jdbc.PoolDataSource.setMinPoolSize(int) for details.
|`network-protocol` |string |{nbsp} |Sets the data source network protocol.
See oracle.ucp.jdbc.PoolDataSource.setNetworkProtocol(String) for details.
|`ons-configuration` |string |{nbsp} |Sets the configuration string used for remote ONS subscription.
See oracle.ucp.jdbc.PoolDataSource.setONSConfiguration(String) for details.
|`port-number` |int |{nbsp} |Sets the database port number.
See oracle.ucp.jdbc.PoolDataSource.setPortNumber(int) for details.
|`property-cycle` |int |{nbsp} |Sets the property cycle in seconds.
See oracle.ucp.jdbc.PoolDataSource.setPropertyCycle(int) for details.
|`query-timeout` |int |{nbsp} |Sets the number of seconds the driver will wait for a Statement object to execute
to the given number of seconds.
See oracle.ucp.jdbc.PoolDataSource.setQueryTimeout(int) for details.
|`read-only-instance-allowed` |boolean |{nbsp} |Sets the read-only instance allowed value on the datasource.
See oracle.ucp.jdbc.PoolDataSource.setReadOnlyInstanceAllowed(boolean) for details.
|`role-name` |string |{nbsp} |Sets the data source role name.
See oracle.ucp.jdbc.PoolDataSource.setRoleName(String) for details.
|`seconds-to-trust-idle-connection` |int |{nbsp} |Sets the time to trust an idle connection to skip a validation test in seconds.
See oracle.ucp.jdbc.PoolDataSource.setSecondsToTrustIdleConnection(int) for details.
|`server-name` |string |{nbsp} |Sets the database server name.
See oracle.ucp.jdbc.PoolDataSource.setServerName(String) for details.
|`sharding-mode` |boolean |{nbsp} |Change the mode of UCP when UCP is using a Sharded Database.
See oracle.ucp.jdbc.PoolDataSource.setShardingMode(boolean) for details.
|`sql-for-validate-connection` |string |{nbsp} |Sets the SQL statement to validate the database connection.
See oracle.ucp.jdbc.PoolDataSource.setSQLForValidateConnection(String) for details.
|`time-to-live-connection-timeout` |int |{nbsp} |Sets the maximum time a connection may remain in-use in seconds.
See oracle.ucp.jdbc.PoolDataSource.setTimeToLiveConnectionTimeout(int) for details.
|`timeout-check-interval` |int |{nbsp} |Sets the timeout check interval in seconds.
See oracle.ucp.jdbc.PoolDataSource.setTimeoutCheckInterval(int) for details.
|`validate-connection-on-borrow` |boolean |{nbsp} |Makes the pool validate the connection before returning it to the user by calling the JDBC API `isValid`.
See oracle.ucp.jdbc.PoolDataSource.setValidateConnectionOnBorrow(boolean) for details.
|`xa-data-source` |boolean |{nbsp} |Support for distributed transactions.
oracle.ucp.jdbc.PoolXADataSource instance is returned when `true`,
oracle.ucp.jdbc.PoolDataSource instance is returned when `false`.
Default value is `false`.

|===

// end::config[]