///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.langchain4j.McpClientConfig
:keywords: helidon, config, io.helidon.integrations.langchain4j.McpClientConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.langchain4j.McpClientConfig
include::{rootdir}/includes/attributes.adoc[]

= McpClientConfig (integrations.langchain4j) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.langchain4j/io/helidon/integrations/langchain4j/McpClientConfig.html[io.helidon.integrations.langchain4j.McpClientConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`client-name` |string |{nbsp} |Sets the name that the client will use to identify itself to the
MCP server in the initialization message.
Overwrites the default client name from langchain4j.
|`client-version` |string |{nbsp} |Sets the version string that the client will use to identify
itself to the MCP server in the initialization message.
Overwrites the default client version from langchain4j.
|`initialization-timeout` |Duration |{nbsp} |Sets the timeout for initializing the client.
Overwrites the default timeout for initializing from langchain4j.
|`key` |string |{nbsp} |Sets a unique identifier for the client. If none is provided, a
UUID will be automatically generated. This key is later used to identify the client
in the service registry.
|`log-requests` |boolean |{nbsp} |Whether to log request traffic.
|`log-responses` |boolean |{nbsp} |Whether to log response traffic.
|`ping-timeout` |Duration |{nbsp} |The timeout to apply when waiting for a ping response.
Overwrites the default timeout when waiting for a ping response from langchain4j.
|`prompts-timeout` |Duration |{nbsp} |The timeout for prompt-related operations (listing prompts as well as rendering the contents of a prompt).
A value of zero means no timeout.
Overwrites the default timeout for prompt-related operations from langchain4j.
|`protocol-version` |string |{nbsp} |Sets the protocol version that the client will advertise in the
initialization message. Overwrites the default version from langchain4j.
|`reconnect-interval` |Duration |{nbsp} |The delay before attempting to reconnect after a failed connection.
Overwrites the default reconnect interval from langchain4j.
|`resources-timeout` |Duration |{nbsp} |Sets the timeout for resource-related operations (listing resources as well as reading the contents of a resource).
A value of zero means no timeout.
Overwrites the default timeout for resource-related operations from langchain4j.
|`sse-uri` |URI |{nbsp} |The initial URI where to connect to the server and request a SSE
channel.
|`tool-execution-timeout` |Duration |{nbsp} |Sets the timeout for tool execution.
This value applies to each tool execution individually.
A value of zero means no timeout.
Overwrites the default timeout for tool execution from langchain4j.
|`tool-execution-timeout-error-message` |string |{nbsp} |The error message to return when a tool execution times out.
Overwrites the default error message from langchain4j.

|===

// end::config[]