///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.oidc.common.ClientCredentialsConfig
:keywords: helidon, config, io.helidon.security.providers.oidc.common.ClientCredentialsConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.oidc.common.ClientCredentialsConfig
include::{rootdir}/includes/attributes.adoc[]

= ClientCredentialsConfig (security.providers.oidc.common) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.security.providers.oidc.common/io/helidon/security/providers/oidc/common/ClientCredentialsConfig.html[io.helidon.security.providers.oidc.common.ClientCredentialsConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`scope` |string |{nbsp} |Scope used when obtaining access token in the client credentials flow.
It is required to set when `server-type` is set to `idcs`.

|===

// end::config[]