///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.langchain4j.AiServicesConfig
:keywords: helidon, config, io.helidon.integrations.langchain4j.AiServicesConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.langchain4j.AiServicesConfig
include::{rootdir}/includes/attributes.adoc[]

= AiServicesConfig (integrations.langchain4j) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.langchain4j/io/helidon/integrations/langchain4j/AiServicesConfig.html[io.helidon.integrations.langchain4j.AiServicesConfig]


This is a standalone configuration type, prefix from configuration root: `langchain4j.services`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`chat-model` |string |{nbsp} |

|===

// end::config[]