///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.concurrency.limits.FixedLimit
:keywords: helidon, config, io.helidon.common.concurrency.limits.FixedLimit
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.concurrency.limits.FixedLimit
include::{rootdir}/includes/attributes.adoc[]

= FixedLimit (common.concurrency.limits) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.concurrency.limits/io/helidon/common/concurrency/limits/FixedLimit.html[io.helidon.common.concurrency.limits.FixedLimit]


[source,text]
.Config key
----
fixed
----


This type provides the following service implementations:

- `io.helidon.common.concurrency.limits.spi.LimitProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enable-metrics` |boolean |`false` |Whether to collect metrics for the fixed limit implementation.
|`fair` |boolean |`false` |Whether the java.util.concurrent.Semaphore should be java.util.concurrent.Semaphore.isFair().
Defaults to `false`.
|`permits` |int |`0` |Number of permit to allow.
Defaults to `0`.
When set to `0`, we switch to unlimited.
|`queue-length` |int |`0` |How many requests can be enqueued waiting for a permit.
Note that this may not be an exact behavior due to concurrent invocations.
We use java.util.concurrent.Semaphore.getQueueLength() in the
io.helidon.common.concurrency.limits.FixedLimit implementation.
Default value is `0`.
If set to {code 0}, there is no queueing.
|`queue-timeout` |Duration |`PT1S` |How long to wait for a permit when enqueued.
Defaults to `PT1S`

|===

// end::config[]