///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.metrics.api.MetricsConfig
:keywords: helidon, config, io.helidon.metrics.api.MetricsConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.MetricsConfig
include::{rootdir}/includes/attributes.adoc[]

= MetricsConfig (metrics.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.metrics.api/io/helidon/metrics/api/MetricsConfig.html[io.helidon.metrics.api.MetricsConfig]


This is a standalone configuration type, prefix from configuration root: `metrics`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`app-name` |string |{nbsp} |Value for the application tag to be added to each meter ID.
|`app-tag-name` |string |{nbsp} |Name for the application tag to be added to each meter ID.
|`built-in-meter-name-format` |BuiltInMeterNameFormat (SNAKE, CAMEL) |`BuiltInMeterNameFormat.CAMEL` |Output format for built-in meter names.

BuiltInMeterNameFormat.SNAKE selects "snake_case" which does not conform to the MicroProfile
Metrics specification.

Allowed values:

- `SNAKE`: Snake-case.
- `CAMEL`: Camel-case (which is compatible with the MicroProfile Metrics spec).

|`enabled` |boolean |`true` |Whether metrics functionality is enabled.
|[.line-through]#`gc-time-type`# |GcTimeType (GAUGE, COUNTER) |`GcTimeType.COUNTER` |*Deprecated* Whether the `gc.time` meter should be registered as a gauge (vs. a counter).
The `gc.time` meter is inspired by the MicroProfile Metrics spec, in which the meter was originally checked to
be a counter but starting in 5.1 was checked be a gauge. For the duration of Helidon 4.x users can choose which
type of meter Helidon registers for `gc.time`.

@deprecated Provided for backward compatibility only; no replacement

Allowed values:

- `GAUGE`: Implement the meter as a gauge. This is backward-incompatible with Helidon 4.0.x releases but complies with
MicroProfile 5.1.
- `COUNTER`: Implement the meter as a counter. This is backward-compatible with Helidon 4.0.x releases but does not comply with
MicroProfile 5.1.

|`key-performance-indicators` |xref:{rootdir}/config/io_helidon_metrics_api_KeyPerformanceIndicatorMetricsConfig.adoc[KeyPerformanceIndicatorMetricsConfig] |{nbsp} |Key performance indicator metrics settings.
|`permit-all` |boolean |`true` |Whether to allow anybody to access the endpoint.

See roles()
|[.line-through]#`rest-request-enabled`# |boolean |{nbsp} |*Deprecated* Whether automatic REST request metrics should be measured (as indicated by the deprecated config
key `rest-request-enabled`, the config key using a hyphen instead of a dot separator).

@deprecated Use `rest-request.enabled` instead.
|`rest-request.enabled` |boolean |`false` |Whether automatic REST request metrics should be measured.
|`roles` |string[&#93; |`observe` |Hints for role names the user is expected to be in.
|`scoping` |xref:{rootdir}/config/io_helidon_metrics_api_ScopingConfig.adoc[ScopingConfig] |{nbsp} |Settings related to scoping management.
|`tags` |xref:{rootdir}/config/io_helidon_metrics_api_Tag.adoc[Tag[&#93;] |{nbsp} |Global tags.
|`timers.json-units-default` |TimeUnit (NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS) |{nbsp} |Default units for timer output in JSON if not specified on a given timer.

If the configuration key is absent, the Helidon JSON output uses java.util.concurrent.TimeUnit.SECONDS.
If the configuration key is present, Helidon formats each timer using that timer's specific units (if set) and
the config value otherwise.
|`virtual-threads.enabled` |boolean |`false` |Whether Helidon should expose meters related to virtual threads.
|`virtual-threads.pinned.threshold` |Duration |`PT0.020S` |Threshold for sampling pinned virtual threads to include in the pinned threads meter.
|`warn-on-multiple-registries` |boolean |`true` |Whether to log warnings when multiple registries are created.

By far most applications use a single meter registry, but certain app or library programming errors can cause Helidon to
create more than one. By default, Helidon logs warning messages for each additional meter registry created. This
setting allows users with apps that <em>need</em> multiple meter registries to suppress those warnings.

|===

// end::config[]