///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.grpc.GrpcConfig
:keywords: helidon, config, io.helidon.webserver.grpc.GrpcConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.grpc.GrpcConfig
include::{rootdir}/includes/attributes.adoc[]

= GrpcConfig (webserver.grpc) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.grpc/io/helidon/webserver/grpc/GrpcConfig.html[io.helidon.webserver.grpc.GrpcConfig]


[source,text]
.Config key
----
grpc
----


This type provides the following service implementations:

- `io.helidon.webserver.spi.ProtocolConfigProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enable-compression` |boolean |`true` |Whether to support compression if requested by a client. If explicitly
disabled, no compression will ever be used by the server even if a
client-compatible compressor is found.
|`enable-metrics` |boolean |`false` |Whether to collect metrics for gRPC server calls.
|`max-read-buffer-size` |int |`2097152` |Max size of gRPC reading buffer. If receiving an entity larger than this,
processing will be aborted. This can help prevent DoS attacks. Default
set to 2 MB.

|===

// end::config[]