///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.langchain4j.providers.mock.MockChatModel
:keywords: helidon, config, io.helidon.integrations.langchain4j.providers.mock.MockChatModel
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.langchain4j.providers.mock.MockChatModel
include::{rootdir}/includes/attributes.adoc[]

= MockChatModel (integrations.langchain4j.providers.mock) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.langchain4j.providers.mock/io/helidon/integrations/langchain4j/providers/mock/MockChatModel.html[io.helidon.integrations.langchain4j.providers.mock.MockChatModel]


This is a standalone configuration type, prefix from configuration root: `langchain4j.providers.mock`



== Configuration options



// end::config[]