///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.discovery.providers.eureka.EurekaDiscovery
:keywords: helidon, config, io.helidon.discovery.providers.eureka.EurekaDiscovery
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.discovery.providers.eureka.EurekaDiscovery
include::{rootdir}/includes/attributes.adoc[]

= EurekaDiscovery (discovery.providers.eureka) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.discovery.providers.eureka/io/helidon/discovery/providers/eureka/EurekaDiscovery.html[io.helidon.discovery.providers.eureka.EurekaDiscovery]


[source,text]
.Config key
----
eureka
----



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cache` |xref:{rootdir}/config/io_helidon_discovery_providers_eureka_CacheConfig.adoc[CacheConfig] |`io.helidon.discovery.providers.eureka.EurekaDiscoveryConfigBlueprint.create()` |The CacheConfig to use controlling how a local cache of Eureka server information is used.

See CacheConfig
|`client` |xref:{rootdir}/config/io_helidon_webclient_http1_Http1Client.adoc[Http1Client] |{nbsp} |The Http1Client to use to communicate with the Eureka server.
To be useful, the client must have a io.helidon.webclient.http1.Http1ClientConfig prototype whose
io.helidon.webclient.http1.Http1ClientConfig.Builder.baseUri(io.helidon.webclient.api.ClientUri) property
is set to the endpoint of a Eureka Server instance. Often this value will be something like {@code
http://example.com:8761/eureka}.

See Http1Client

See io.helidon.webclient.http1.Http1ClientConfig.Builder.baseUri(io.helidon.webclient.api.ClientUri)
|`prefer-ip-address` |boolean |{nbsp} |Whether the <dfn>host</dfn> component of any java.net.URI URI should be set to the IP address stored by
Eureka, or the hostname; `false` by default.

|===

// end::config[]