///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.ErrorHandling
:keywords: helidon, config, io.helidon.webserver.ErrorHandling
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.ErrorHandling
include::{rootdir}/includes/attributes.adoc[]

= ErrorHandling (webserver) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver/io/helidon/webserver/ErrorHandling.html[io.helidon.webserver.ErrorHandling]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`include-entity` |boolean |`false` |Whether to include a response entity when mapping a io.helidon.http.RequestException
using a io.helidon.http.DirectHandler. Response entities may include data that
is reflected back from the original request, albeit escaped to prevent potential attacks.
|`log-all-messages` |boolean |`false` |Whether to log all messages in a io.helidon.http.RequestException or not.
If set to `false`, only those that return `true` for
io.helidon.http.RequestException.safeMessage() are logged.

|===

// end::config[]