///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.telemetry.otelconfig.SpanProcessorConfig
:keywords: helidon, config, io.helidon.telemetry.otelconfig.SpanProcessorConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.telemetry.otelconfig.SpanProcessorConfig
include::{rootdir}/includes/attributes.adoc[]

= SpanProcessorConfig (telemetry.otelconfig) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.telemetry.otelconfig/io/helidon/telemetry/otelconfig/SpanProcessorConfig.html[io.helidon.telemetry.otelconfig.SpanProcessorConfig]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`type` |SpanProcessorType (SIMPLE, BATCH) |{nbsp} |Span processor type.

Allowed values:

- `SIMPLE`: Simple Span Processor.
- `BATCH`: Batch Span Processor.


|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`exporters` |string[&#93; |{nbsp} |Name(s) of the span exporter(s) this span processor should use; specifying no names uses all configured exporters (or
if no exporters are configured, the default OpenTelemetry exporter(s)).

Each name must be the name of one of the configured OpenTelemetryTracingConfig.exporterConfigs().

|===

// end::config[]