///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.data.sql.datasource.hikari.HikariDataSourceConfig
:keywords: helidon, config, io.helidon.data.sql.datasource.hikari.HikariDataSourceConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.data.sql.datasource.hikari.HikariDataSourceConfig
include::{rootdir}/includes/attributes.adoc[]

= HikariDataSourceConfig (data.sql.datasource.hikari) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.data.sql.datasource.hikari/io/helidon/data/sql/datasource/hikari/HikariDataSourceConfig.html[io.helidon.data.sql.datasource.hikari.HikariDataSourceConfig]


[source,text]
.Config key
----
hikari
----


This type provides the following service implementations:

- `io.helidon.data.sql.datasource.spi.DataSourceConfigProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`allow-pool-suspension` |boolean |{nbsp} |Set whether pool suspension is allowed.
See com.zaxxer.hikari.HikariConfig.setAllowPoolSuspension(boolean) for details.
|`auto-commit` |boolean |{nbsp} |Set the default auto-commit behavior of connections in the pool.
See com.zaxxer.hikari.HikariConfig.setAutoCommit(boolean) for details.
|`catalog` |string |{nbsp} |Set the default catalog name to be set on connections.
See com.zaxxer.hikari.HikariConfig.setCatalog(String) for details.
|`connection-init-sql` |string |{nbsp} |Set the SQL string that will be executed on all new connections when they are created,
before they are added to the pool.
See com.zaxxer.hikari.HikariConfig.setConnectionInitSql(String) for details.
|`connection-test-query` |string |{nbsp} |Set the SQL query to be executed to test the validity of connections.
See com.zaxxer.hikari.HikariConfig.setConnectionTestQuery(String) for details.
|`connection-timeout` |long |{nbsp} |Set the maximum number of milliseconds that a client will wait for a connection from the pool.
See com.zaxxer.hikari.HikariConfig.setConnectionTimeout(long) for details.
|`health-check-properties` |Map&lt;string, string&gt; |{nbsp} |Add properties (name/value pair) that will be used to configure the connection pool health check.
See com.zaxxer.hikari.HikariConfig.addHealthCheckProperty(String, String) for details.
|`idle-timeout` |long |{nbsp} |This property controls the maximum amount of time that a connection is allowed to sit idle in the pool.
See com.zaxxer.hikari.HikariConfig.setIdleTimeout(long) for details.
|`initialization-fail-timeout` |long |{nbsp} |Set the pool initialization failure timeout.
See com.zaxxer.hikari.HikariConfig.setInitializationFailTimeout(long) for details.
|`isolate-internal-queries` |boolean |{nbsp} |Configure whether internal pool queries, principally aliveness checks, will be isolated
in their own transaction via java.sql.Connection.rollback().
See com.zaxxer.hikari.HikariConfig.setIsolateInternalQueries(boolean) for details.
|`keepalive-time` |long |{nbsp} |This property controls the keepalive interval for a connection in the pool.
See com.zaxxer.hikari.HikariConfig.setKeepaliveTime(long) for details.
|`leak-detection-threshold` |long |{nbsp} |This property controls the amount of time that a connection can be out of the pool
before a message is logged indicating a possible connection leak.
See com.zaxxer.hikari.HikariConfig.setLeakDetectionThreshold(long) for details.
|`max-lifetime` |long |{nbsp} |This property controls the maximum lifetime of a connection in the pool.
See com.zaxxer.hikari.HikariConfig.setMaxLifetime(long) for details.
|`maximum-pool-size` |int |{nbsp} |The property controls the maximum size that the pool is allowed to reach, including
both idle and in-use connections.
See com.zaxxer.hikari.HikariConfig.setMaximumPoolSize(int) for details.
|`minimum-idle` |int |{nbsp} |The property controls the minimum number of idle connections that HikariCP tries to maintain
in the pool, including both idle and in-use connections.
See com.zaxxer.hikari.HikariConfig.setMinimumIdle(int) for details.
|`pool-name` |string |{nbsp} |Set the name of the connection pool.
See com.zaxxer.hikari.HikariConfig.setPoolName(String) for details.
|`properties` |Map&lt;string, string&gt; |{nbsp} |Add properties (name/value pair) that will be used to configure the DataSource/Driver.
Property values are limited to String values.
See com.zaxxer.hikari.HikariConfig.addDataSourceProperty(String, Object) for details.
|`read-only` |boolean |{nbsp} |Configures the Connections to be added to the pool as read-only Connections.
See com.zaxxer.hikari.HikariConfig.setReadOnly(boolean) for details.
|`register-mbeans` |boolean |{nbsp} |Configures whether HikariCP self-registers the com.zaxxer.hikari.HikariConfigMXBean
and com.zaxxer.hikari.HikariPoolMXBean in JMX.
See com.zaxxer.hikari.HikariConfig.setRegisterMbeans(boolean) for details.
|`schema` |string |{nbsp} |Set the default schema name to be set on connections.
See com.zaxxer.hikari.HikariConfig.setSchema(String) for details.
|`transaction-isolation` |TransactionIsolation (TRANSACTION_READ_UNCOMMITTED, TRANSACTION_READ_COMMITTED, TRANSACTION_REPEATABLE_READ, TRANSACTION_SERIALIZABLE) |{nbsp} |Set the default transaction isolation level.
See com.zaxxer.hikari.HikariConfig.setTransactionIsolation(String) for details.
|`validation-timeout` |long |{nbsp} |Sets the maximum number of milliseconds that the pool will wait for a connection to be validated as alive.
See com.zaxxer.hikari.HikariConfig.setValidationTimeout(long) for details.

|===

// end::config[]