///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.staticcontent.TemporaryStorage
:keywords: helidon, config, io.helidon.webserver.staticcontent.TemporaryStorage
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.staticcontent.TemporaryStorage
include::{rootdir}/includes/attributes.adoc[]

= TemporaryStorage (webserver.staticcontent) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.staticcontent/io/helidon/webserver/staticcontent/TemporaryStorage.html[io.helidon.webserver.staticcontent.TemporaryStorage]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`delete-on-exit` |boolean |`true` |Whether temporary files should be deleted on JVM exit.
This is enabled by default, yet it may be useful for debugging purposes to keep the files in place.
|`directory` |Path |{nbsp} |Location of the temporary storage, defaults to temporary storage configured for the JVM.
|`enabled` |boolean |`true` |Whether the temporary storage is enabled, defaults to `true`.
If disabled, nothing is stored in temporary directory (may have performance impact, as for example a file may be
extracted from a zip file on each request).
|`file-prefix` |string |`helidon-ws` |Prefix of the files in temporary storage.
|`file-suffix` |string |`.je` |Suffix of the files in temporary storage.

|===

// end::config[]