///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.staticcontent.MemoryCache
:keywords: helidon, config, io.helidon.webserver.staticcontent.MemoryCache
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.staticcontent.MemoryCache
include::{rootdir}/includes/attributes.adoc[]

= MemoryCache (webserver.staticcontent) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.staticcontent/io/helidon/webserver/staticcontent/MemoryCache.html[io.helidon.webserver.staticcontent.MemoryCache]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`capacity` |Size |`50 mB` |Capacity of the cached bytes of file content.
If set to `0`, the cache is unlimited. To disable caching, set enabled() to `false`,
or do not configure a memory cache at all.

The capacity must be less than java.lang.Long.MAX_VALUE bytes, though you must be careful still,
as it must fit into the heap size.
|`enabled` |boolean |`true` |Whether the cache is enabled, defaults to `true`.

|===

// end::config[]