///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.concurrency.limits.ThroughputLimit
:keywords: helidon, config, io.helidon.common.concurrency.limits.ThroughputLimit
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.concurrency.limits.ThroughputLimit
include::{rootdir}/includes/attributes.adoc[]

= ThroughputLimit (common.concurrency.limits) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.concurrency.limits/io/helidon/common/concurrency/limits/ThroughputLimit.html[io.helidon.common.concurrency.limits.ThroughputLimit]


[source,text]
.Config key
----
throughput
----


This type provides the following service implementations:

- `io.helidon.common.concurrency.limits.spi.LimitProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`amount` |int |`0` |Number of operations to allow during the relevant time window.
Defaults to `0`.
When set to `0`, we switch to unlimited.
|`duration` |Duration |`PT1S` |Duration of the time window over which operations will be counted.
Defaults to `PT1S`
|`enable-metrics` |boolean |`false` |Whether to collect metrics for the throughput limit implementation.
|`fair` |boolean |`false` |Whether the java.util.concurrent.Semaphore should be java.util.concurrent.Semaphore.isFair().
Defaults to `false`.
|`queue-length` |int |`0` |How many requests can be enqueued waiting for a permit.
Note that this may not be an exact behavior due to concurrent invocations.
We use java.util.concurrent.Semaphore.getQueueLength() in the
io.helidon.common.concurrency.limits.ThroughputLimit implementation.
Default value is `0`.
If set to {code 0}, there is no queueing.
|`queue-timeout` |Duration |`PT1S` |How long to wait for a permit when enqueued.
Defaults to `PT1S`
|`rate-limiting-algorithm` |RateLimitingAlgorithmType (TOKEN_BUCKET, FIXED_RATE) |`RateLimitingAlgorithmType.TOKEN_BUCKET` |The rate limiting algorithm to apply.

Rate limiting algorithm is by default RateLimitingAlgorithmType.TOKEN_BUCKET.

Allowed values:

- `TOKEN_BUCKET`: Requests require tokens from a bucket that fills over time.
- `FIXED_RATE`: Requests are processed at a fixed rate.


|===

// end::config[]